# Advanced DNS Server Configuration
# Comprehensive configuration with all features enabled

# Server configuration
server:
  address: "0.0.0.0:53"
  read_timeout: 10s
  write_timeout: 10s
  max_connections: 10000
  enable_tcp: true
  enable_udp: true
  enable_metrics: true
  enable_health: true

# Resolver configuration
resolver:
  type: "cache"  # Use caching resolver
  timeout: 10s
  max_retries: 5
  forward_servers:
    - "8.8.8.8:53"
    - "8.8.4.4:53"
    - "1.1.1.1:53"
    - "9.9.9.9:53"
    - "208.67.222.222:53"  # OpenDNS
    - "208.67.220.220:53"  # OpenDNS
  root_servers:
    - "a.root-servers.net:53"
    - "b.root-servers.net:53"
    - "c.root-servers.net:53"
    - "d.root-servers.net:53"
    - "e.root-servers.net:53"
    - "f.root-servers.net:53"
    - "g.root-servers.net:53"
    - "h.root-servers.net:53"
    - "i.root-servers.net:53"
    - "j.root-servers.net:53"
    - "k.root-servers.net:53"
    - "l.root-servers.net:53"
    - "m.root-servers.net:53"
  recursion_depth: 20

# Storage configuration
storage:
  type: "sqlite"
  dsn: "/var/lib/dnska/dnska.db"
  max_conns: 50

# API configuration
api:
  enabled: true
  address: "127.0.0.1:8080"
  enable_rest: true
  enable_grpc: true
  auth_enabled: true

# Logging configuration
logging:
  level: "debug"
  format: "json"
  output: "/var/log/dnska/dnska.log"

# Cache configuration
cache:
  enabled: true
  size: 10000
  ttl: 600s  # 10 minutes
  type: "ttl"

# Comprehensive zone configurations
zones:
  # Local development zone
  - name: "local"
    records:
      - name: "@"
        type: "A"
        value: "127.0.0.1"
        ttl: 300
      - name: "api"
        type: "A"
        value: "127.0.0.1"
        ttl: 300
      - name: "db"
        type: "A"
        value: "127.0.0.1"
        ttl: 300
      - name: "redis"
        type: "A"
        value: "127.0.0.1"
        ttl: 300

  # Production zone with full DNS setup
  - name: "example.com"
    records:
      # Root records
      - name: "@"
        type: "A"
        value: "203.0.113.1"
        ttl: 300
      - name: "@"
        type: "AAAA"
        value: "2001:db8::1"
        ttl: 300

      # WWW records
      - name: "www"
        type: "CNAME"
        value: "@"
        ttl: 300

      # Mail records
      - name: "@"
        type: "MX"
        value: "10 mail.example.com"
        ttl: 3600
      - name: "@"
        type: "MX"
        value: "20 mail2.example.com"
        ttl: 3600
      - name: "mail"
        type: "A"
        value: "203.0.113.10"
        ttl: 300
      - name: "mail"
        type: "AAAA"
        value: "2001:db8::10"
        ttl: 300
      - name: "mail2"
        type: "A"
        value: "203.0.113.11"
        ttl: 300

      # Name servers
      - name: "@"
        type: "NS"
        value: "ns1.example.com"
        ttl: 86400
      - name: "@"
        type: "NS"
        value: "ns2.example.com"
        ttl: 86400
      - name: "ns1"
        type: "A"
        value: "203.0.113.53"
        ttl: 300
      - name: "ns2"
        type: "A"
        value: "203.0.113.54"
        ttl: 300

      # Security records
      - name: "@"
        type: "TXT"
        value: "v=spf1 mx -all"
        ttl: 3600
      - name: "_dmarc"
        type: "TXT"
        value: "v=DMARC1; p=quarantine; rua=mailto:dmarc@example.com"
        ttl: 3600
      - name: "_domainkey"
        type: "TXT"
        value: "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC..."
        ttl: 3600

      # Service discovery
      - name: "_http._tcp"
        type: "SRV"
        value: "0 5 80 web.example.com"
        ttl: 300
      - name: "_https._tcp"
        type: "SRV"
        value: "0 5 443 web.example.com"
        ttl: 300

  # Reverse DNS zone
  - name: "113.0.203.in-addr.arpa"
    records:
      - name: "1"
        type: "PTR"
        value: "example.com"
        ttl: 300
      - name: "10"
        type: "PTR"
        value: "mail.example.com"
        ttl: 300
      - name: "53"
        type: "PTR"
        value: "ns1.example.com"
        ttl: 300

  # IPv6 reverse DNS zone
  - name: "0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa"
    records:
      - name: "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0"
        type: "PTR"
        value: "example.com"
        ttl: 300

  # SOA record example
  - name: "soa.example.com"
    records:
      - name: "@"
        type: "SOA"
        value: "ns1.example.com admin.example.com 2023120101 3600 1800 604800 86400"
        ttl: 3600
      - name: "@"
        type: "NS"
        value: "ns1.example.com"
        ttl: 3600
      - name: "ns1"
        type: "A"
        value: "203.0.113.53"
        ttl: 300
