name: Go Version Compatibility

on:
  # Run on schedule to check compatibility with new Go versions
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday at 2 AM UTC
  # Also allow manual trigger
  workflow_dispatch:
  # Run on changes to go.mod or CI files
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"

env:
  GO_VERSION: "1.25"

jobs:
  compatibility:
    name: Go ${{ matrix.go-version }} Compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23", "1.24", "1.25"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ubuntu-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ubuntu-go-${{ matrix.go-version }}-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run tests (basic)
        run: go test -v ./...
